apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse-ui
  namespace: observable
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - langfuse.example.com
      secretName: observability-tls
  rules:
    - host: langfuse.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langfuse-web
                port:
                  number: 3000

