apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-configs
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
stringData:
  additional-scrape-configs.yaml: |
    - job_name: 'rag_service'
      scrape_interval: 15s
      metrics_path: /metrics
      static_configs:
        - targets:
          - 'localhost:8081'

