{
 "title": "RAG-API Service Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": " In-Flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Latency (per handler)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (handler) / sum(rate(http_request_duration_seconds_count[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "2xx / 5xx Rates by handler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(handler)(rate(http_requests_total{status=~\"2..\"}[5m])) / sum by(handler)(rate(http_requests_total[5m]))",
     "legendFormat": "2xx {{handler}}"
    },
    {
     "expr": "sum by(handler)(rate(http_requests_total{status=~\"5..\"}[5m])) / sum by(handler)(rate(http_requests_total[5m]))",
     "legendFormat": "5xx {{handler}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m])\n  /\nrate(http_request_duration_seconds_count[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(handler)(rate(http_requests_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "P50 / P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le,handler)(rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "P50 {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le,handler)(rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "P95 {{handler}}"
    }
   ]
  }
 ]
}