apiVersion: v1
kind: Service
metadata:
  name: chroma-svc
  namespace: rag-services
  labels:
    app: chroma
spec:
  type: ClusterIP
  selector:
    app: chroma
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
# 3️⃣ your StatefulSet unchanged, but serviceName now points
#    to the headless Service above (name: chroma)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chromadb
  namespace: rag-services
spec:
  serviceName: "chroma"   # <— must match the headless Service name
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
    spec:
      containers:
      - name: chroma
        image: ghcr.io/chroma-core/chroma:latest
        env:
        - name: IS_PERSISTENT
          value: "TRUE"
        volumeMounts:
        - name: data
          mountPath: /chroma/chroma
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Gi